---

- name : install dbconfig-common package
  apt  :
    name  : dbconfig-common
    state : "{{ phpmyadmin_dbconfig_state }}"


- name     : pre-configure PHPMyAdmin database
  template :
    src   : "{{ role_path }}/templates/dbconfig_phpmyadmin.conf.j2"
    dest  : "{{ phpmyadmin_dbconfig_file }}"
    owner : "{{ phpmyadmin_dbconfig_file_owner }}"
    group : "{{ phpmyadmin_dbconfig_file_group }}"
    mode  : "{{ phpmyadmin_dbconfig_file_mode }}"


- name : install phpmyadmin packages
  apt  :
    name  : "{{ item }}"
    state : "{{ phpmyadmin_package_state }}"
  register   : install_phpmyadmin_package
  with_items : "{{ phpmyadmin_packages }}"
